title: Projects
proj1: Walmart Sales Forecasting
proj1details: Details walmart
description: This is a list describing all the projects I have done with links to respective project pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
